name: gnome-2048
adopt-info: gnome-2048
grade: stable
confinement: strict
base: core22

# Launchpad doesn't recognize these fields yet
passthrough:
  license: GPL-3.0+
  title: GNOME 2048

slots:
  # for GtkApplication registration
  gnome-2048:
    interface: dbus
    bus: session
    name: org.gnome.TwentyFortyEight

apps:
  gnome-2048:
    extensions: [gnome]
    command: usr/bin/gnome-2048
    desktop: usr/share/applications/org.gnome.TwentyFortyEight.desktop
    common-id: org.gnome.TwentyFortyEight
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  gnome-2048:
    source: https://gitlab.gnome.org/GNOME/gnome-2048.git
    source-type: git
    source-tag: '3.38.2'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.gnome.TwentyFortyEight.appdata.xml]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      patch -p1 < $CRAFT_PROJECT_DIR/patches/patch1.diff
      sed -i.bak -e "s|'gnome-2048',|'gnome-2048', symlink_media: false,|g" help/meson.build
    build-packages:
      - libc-dev


  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [gnome-2048]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
